{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header"><span class="icon-home"></span> 您现在的位置：<a href="#">首页</a> <span class="divider">/</span> 标签</div>
            <div class="panel-body">
                <ul class="inline">
                    <li class="span2"><a href="/v0.1/yabindex.php/tab/php">phg</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">nodejs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">extjs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">mongodb</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">jquery</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">backbone</a></li>
                </ul>
                <ul class="inline">
                    <li class="span2"><a href="/v0.1/yabindex.php/tab/php">phg</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">nodejs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">extjs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">mongodb</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">jquery</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">backbone</a></li>
                </ul>
                <ul class="inline">
                    <li class="span2"><a href="/v0.1/yabindex.php/tab/php">phg</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">nodejs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">extjs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">mongodb</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">jquery</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">backbone</a></li>
                </ul>
                <ul class="inline">
                    <li class="span2"><a href="/v0.1/yabindex.php/tab/php">phg</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">nodejs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">extjs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">mongodb</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">jquery</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">backbone</a></li>
                </ul>
                <ul class="inline">
                    <li class="span2"><a href="/v0.1/yabindex.php/tab/php">phg</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">nodejs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">extjs</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">mongodb</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">jquery</a></li>
                    <li class="span2"><a class="span2" href="/v0.1/yabindex.php/tab/php">backbone</a></li>
                </ul>
                <div class="pagination pagination-centered">
                    <ul>
                        <li class="disabled"><span>首页</span></li>
                        <li class="disabled"><span>上一页</span></li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">下一页</a></li>
                        <li><a href="#">尾页</a></li>
                    </ul>
                </div>
                <!--end 网文-->
            </div>
        </div><!--end span9-->
        <div class="span3">
            <div class="panel">
                <div class="panel-header"><h3>热门网文</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>网文标签</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>最新留言</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                    </ul>
                </div>
            </div>
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}