{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header"><span class="icon-home"></span> 您现在的位置： <a href="{BASE_SITE_URL}">首页</a> <span class="divider">/</span> <!--#include virtual="/v0.1/ssi/category/nav{$blog_info.cate_id}.shtml"--></div>
            <div class="panel-body">
                <div class="blog-detail">
                    <h1>{$blog_info.title}</h1>
                    <p class="blog-meta">
                        <span>{echo new_date(null, $blog_info['add_time']);}</span>
                        <span>来源：<a href="{$blog_info.from_url}">{$blog_info.from_name}</a></span>
                        <span>阅读：{$blog_info.hits}</span>
                        <span>评论：{$blog_info.comments}</span>
                    </p>
                <div class="blog-content">
                    {$blog_info.content}
    			             <p><span class="icon-tags"></span>标签：<a href="#">php</a>,<a href="#">js</a>,<a href="#">jquery</a></p>
    			             <p class="text-center"><a class="label label-inverse"><span class="icon-thumbs-up icon-white"></span> 顶一个</a></p>

			             </div>

    			             <p>
    			                <span class="pull-right">
    			                    <span class="icon-circle-arrow-right"></span>
    			                    下一篇：<a href="#">php高级技巧</a>
    			                </span>
    			                <span class="icon-circle-arrow-left"></span>
    			                上一篇：<a href="#">php高级技巧</a>
    			             </p>
			             </div>
			             <hr />
			             <div class="row ml-10">
			             <div class="span5">
			             <div class="separation separation-guest-like"><span class="icon-heart"></span> 猜您喜欢</div>
			             <ul>
			                 <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
			             </ul>
			             </div>
			             <div class="span5 pull-right">
			             <div class="separation separation-also-read"><span class="icon-eye-open"></span> 阅读过此文的朋友还阅读了...</div>
			             <ul>
			                 <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
			             </ul>
			             </div>
			             </div>
                <div class="separation-comment">评论列表</div>
                {template 'include', 'comments'}
            </div>
        </div><!--end span9-->
        <div class="span3">
            <div class="panel">
                <div class="panel-header"><h3>热门网文</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>网文标签</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>最新留言</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                    </ul>
                </div>
            </div>
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}