{template 'include', 'header'}
{php $meta_info_arr['blog'] = $blog_info['blog_id'] . '|' . $blog_info['add_time']; }
{php $meta_info_arr['hits'] = 'blog,' . $blog_info['blog_id'] . ',' . $blog_info['add_time']; }
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header">
                <span class="icon-home"></span>
                {L NOW_POSITION}：<a href="{BASE_SITE_URL}">{L HOME}</a>
                <span class="divider">&raquo;</span>
                <!--#include virtual="/v0.1/ssi/category/nav{$blog_info.cate_id}.shtml"-->
                {$blog_info.title}
            </div>
            <div class="panel-body">
                <div class="blog-detail">
                    <h1>{$blog_info.title}</h1>
                    <p class="blog-meta">
                        <span>{echo new_date(null, $blog_info['add_time']);}</span>
                        <span>{L ORIGIN}：<a href="{$blog_info.from_url}">{$blog_info.from_name}</a></span>
                        <span>{L READS}：<small class="counter blog-hits-{$blog_info.blog_id}">{$blog_info.hits}</small></span>
                        <span>{L COMMENTS}：<small class="counter blog-comments-{$blog_info.blog_id}">{$blog_info.comments}</small></span>
                        <span>{L DIGG}：<small class="counter blog-diggs-{$blog_info.blog_id}">{$blog_info.comments}</small></span>
                    </p>
                <div class="blog-content">
                    {$blog_info.content}
                    {if $tags}<p><span class="icon-tags"></span>{L TAG}：{$tags}</p>{/if}
                    <p class="text-center"><a class="label label-inverse"><span class="icon-thumbs-up icon-white"></span> {L DIGG_ONE}</a></p>
                </div>

                    <p>
                       <span class="pull-right">
                           <span class="icon-circle-arrow-right"></span>
                           {L NEXT_BLOG}：
                           {if $next_blog}
                           <a href="{$next_blog.link_url}">{$next_blog.title}</a>
                           {else}
                           {L CN_MEI_YOU_LE}
                           {/if}
                       </span>
                       <span class="icon-circle-arrow-left"></span>
                        {L PREV_BLOG}：
                        {if $prev_blog}<a href="{$prev_blog.link_url}">{$prev_blog.title}</a>
                        {else}
                        {L CN_MEI_YOU_LE}
                        {/if}
                    </p>
                </div>
                <hr />
                <div class="row ml-10">
                {if $relative_blog}
                <div class="span5">
                <div class="separation separation-guest-like"><span class="icon-heart"></span> {L GUEST_YOU_LIKE}</div>
                <ul>
                    {foreach $relative_blog $v}
                    <li><a href="{$v.link_url}">{$v.title}</a></li>
                    {/foreach}
                </ul>
                </div>
                {/if}
                <!--<div class="span5 pull-right">
                <div class="separation separation-also-read"><span class="icon-eye-open"></span> 阅读过此文的朋友还阅读了...</div>
                <ul>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                </ul>
                </div>-->
                </div>
                {if $comments_html}
                <div class="separation-comment">{L COMMENTS,LIST}</div>
                {$comments_html}
                {/if}
                <div class="separation-add-comment">{L CN_FABIAO,MODULE_NAME_COMMENT}</div>
                <form class="form-horizontal form-comment" method="post" action="{BASE_SITE_URL}comments/add.shtml">
                    <div class="control-group">
                        <label class="control-label"><span class="text-error">*</span>{L USERNAME}</label>
                        <div class="controls">
                            <input type="text" name="username" required maxlength="20" />
                            <span class="muted">(<?php echo str_replace('{0}', 20, L('LT_BYTE')) . '，' . L('CN_TO_BYTE'); ?>)</span>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">{L HOMEPAGE}</label>
                        <div class="controls">
                            <input type="url" name="user_homepage" />
                            <span class="muted">({L CN_XUANTIAN})</span>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"><span class="text-error">*</span>{L CONTENT}</label>
                        <div class="controls">
                            <textarea name="content" rows="3" cols="50" class="input-block-level" required></textarea>
                        </div>
                    </div>
                    <div class="controls text-right">
                        <button class="btn btn-primary">{L SUBMIT}</button>
                        <button class="btn">{L CANCEL}</button>
                    </div>
                    <input type="hidden" name="type" value="0" />
                    <input type="hidden" name="parent_id" value="0" />
                    <input type="hidden" name="blog_id" value="{$blog_info.blog_id}" />
                </form>
            </div>
        </div><!--end span9-->
        <div class="span3">
            <!--#include virtual="/v0.1/ssi/hot_blogs.shtml"-->
            <!--#include virtual="/v0.1/ssi/tags.shtml"-->
            <!--#include virtual="/v0.1/ssi/new_guestbooks.shtml"-->
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}