{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel hide">
            <img src="{COMMON_IMGCACHE}images/ok.gif" alt="" />
            {if isset($msg_content)}
            {$msg_content}
            {else}
            {L MESSAGE_CONTENT}
            {/if}
        </div>
        <div class="span3">
            <!--#include virtual="/v0.1/ssi/hot_blogs.shtml"-->
            <!--#include virtual="/v0.1/ssi/tags.shtml"-->
            <!--#include virtual="/v0.1/ssi/new_comments.shtml"-->
        </div>
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}