{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel noborder">
            <div class="panel-body">
                <!--start 微博  -->
                <div class="panel-list media panel-miniblog">
                    <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
                    <div class="media-body">
                        <div class="popover right">
                            <div class="arrow"></div>
                            <div class="popover-content">
                                <span class="muted">2013-02-15 13:27:03</span>
                                <a href="miniblog-detail.php">微博详情</a>
                                <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                                <p class="text-right actions">
                                    <a href="#" class="muted">
                                        <span class="icon-thumbs-up icon-gray"></span>
                                        <span class="counter">0</span>
                                    </a>
                                    <a href="#" class="muted"><span class="icon-comment icon-gray"></span><span class="counter">0</span></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end 微博-->

                <!--start 网文-->
                <div class="panel-list">
                    <h3><a href="#">文章标题</a></h3>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</p>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息...<a href="#">全文</a></p>
                    <p class="text-right actions">
                        <span class="muted">2013-02-21 11:32:50</span>
                        <a href="#" class="muted">
                            <span class="icon-thumbs-up icon-gray"></span>
                            <span class="counter">0</span>
                        </a>
                        <a href="#" class="muted"><span class="icon-comment icon-gray"></span><span class="counter">0</span></a>
                    </p>
                </div>
                <div class="panel-list">
                    <h3><a href="#">文章标题</a></h3>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</p>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息...<a href="#">全文</a></p>
                    <p class="text-right actions">
                        <span class="muted">2013-02-21 11:32:50</span>
                        <a href="#" class="muted">
                            <span class="icon-thumbs-up icon-gray"></span>
                            <span class="counter">0</span>
                        </a>
                        <a href="#" class="muted"><span class="icon-comment icon-gray"></span><span class="counter">0</span></a>
                    </p>
                </div>
                <div class="panel-list">
                    <h3><a href="#">文章标题</a></h3>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</p>
                    <p>内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息...<a href="#">全文</a></p>
                    <p class="text-right actions">
                        <span class="muted">2013-02-21 11:32:50</span>
                        <a href="#" class="muted">
                            <span class="icon-thumbs-up icon-gray"></span>
                            <span class="counter">0</span>
                        </a>
                        <a href="#" class="muted"><span class="icon-comment icon-gray"></span><span class="counter">0</span></a>
                    </p>
                </div>
                <!--end 网文-->
            </div>
        </div><!--end span9-->
        <div class="span3">
            <div class="panel">
                <div class="panel-header"><h3>热门网文</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>网文标签</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>最新留言</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                    </ul>
                </div>
            </div>
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}