</div><!--end #wrap-->

<!--#include virtual="/v0.1/ssi/footer.shtml"-->
<script>
    var NAV_ID = '{echo isset($nav_id) ? $nav_id : "index"; }';
    {if isset($meta_info_arr)}
    var META_INFO = {php echo json_encode($meta_info_arr);};
    {/if}
</script>
{echo js('System.js,lang/zh_cn.js', false, BASE_SITE_URL . 'static/js/'); }
<script src="{COMMON_IMGCACHE}js/seajs/sea-2.0.1.js" id="seajsnode" data-main="{IMGCACHE_JS}global"></script>
{if 'Blog' == CONTROLLER_NAME && 'detail' == ACTION_NAME}
<script>
var jiathis_config = { data_track_clickback: 'true' };
</script>
<script src="http://v3.jiathis.com/code/jiathis_r.js?move=0&amp;btn=r2.gif&amp;uid=1368583821073501" charset="utf-8"></script>
{/if}
</body>
</html>