<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>留言 | yablog,一个关注web开发的博客</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="php,yaf,nodejs,blog" />
    <meta name="description" content="yet another blog,是的,又一个博客,一个关注web开发的博客" />
    <meta name="author" content="mrmsl" />
    {{'yablog.css'|css:$IMGCACHE_CSS}}
</head>
<body>
<div id="wrap">
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="brand" href="yablog.php">yablog</a>
                <ul class="nav">
                    <li class="active"><a href="yablog.php">首页</a></li>
                    <li><a href="miniblog.php">微博</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="blog.php">网文<span class="caret"></span></a>
                        <ul class="dropdown-menu" id="swatch-menu">
                            <li class="dropdown-submenu">
                                <a href="blog.php">开发语言</a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">php</a></li>
                                    <li class="dropdown-submenu">
                                        <a href="#">js</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#">javascript</a></li>
                                            <li><a href="#">jQuery</a></li>
                                            <li><a href="#">Extjs</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#">nodejs</a></li>
                                </ul>
                            </li>
                            <li class="dropdown-submenu">
                                <a href="#">数据库</a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">mysql</a>
                                        <a href="#">mongodb</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="resource.php">资源</a></li>
                    <li><a href="guestbook.php">留言</a></li>
                    <li><a href="about.php">关于</a></li>
                    <li><a href="contact.php">联系</a></li>
                </ul>
            </div>
        </div>
    </div>