<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{echo !empty($page) ? sprintf(L('N_PAGES'), $page) . ' | ' : '', isset($web_title) ? $web_title : '';} | {$sys_base_web_title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="{echo isset($seo_keywords) ? $seo_keywords : '';}" />
    <meta name="description" content="{echo isset($seo_description) ? $seo_description : '';}" />
    <meta name="author" content="mrmsl" />
    {echo css('yablog.css', IMGCACHE_CSS); }
</head>
<body class="hide0">
<div id="wrap">
    <!--#include virtual="/v0.1/ssi/navbar.shtml"-->