{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header"><span class="icon-home"></span> 您现在的位置：<a href="#">首页</a> <span class="divider">/</span> 留言</div>
            <div class="panel-body">
                {{include file="../include/comments.phtml"}}
            </div>
        </div><!--end span9-->
        <div class="span3">
            <div class="panel">
                <div class="panel-header"><h3>热门网文</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>网文标签</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>最新留言</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                    </ul>
                </div>
            </div>
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}