{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header">
                <span class="icon-home"></span>
                {L NOW_POSITION}：<a href="{BASE_SITE_URL}">{L HOME}</a>
                <span class="divider">&raquo;</span>
                {if '' === $tag}
                {if $cate_info['parent_id']}<!--#include virtual="/v0.1/ssi/category/nav{$cate_info.parent_id}.shtml"-->{/if}
                {$cate_info.cate_name}
                {else}
                <a href="{BASE_SITE_URL}tag.shtml">{L TAG}</a>
                <span class="divider">&raquo;</span>
                {$tag}
                {/if}
            </div>
            <div class="panel-body">
                <!--start 网文-->
                {php $meta_info_arr = array('blog' => ''); }
                {foreach $blog_arr $item}
                {php $meta_info_arr['blog'] .= ',' . $item['blog_id'] . '|' . $item['add_time'];}
                <div class="panel-list">
                    <h3><a href="{$item.link_url}">{$item.title}</a></h3>
                    {$item.summary}
                    <p class="text-right muted">
                        <span class="actions">
                            <span class="icon-time icon-gray"></span>{echo new_date(null, $item['add_time']);}
                            <span class="icon-zoom-in icon-gray ml-10"></span>
                            <span class="counter blog-hits-{$item.blog_id}">0</span>
                            <a href="javascript: void(0)" rel="nofollow" class="blog-diggs muted">
                                <span class="icon-thumbs-up icon-gray"></span>
                                <span class="counter blog-diggs-{$item.blog_id}">0</span>
                            </a>
                            <a href="javascript: void(0)" rel="nofollow" class="muted blog-comments">
                                <span class="icon-comment icon-gray"></span>
                                <span class="counter blog-comments-{$item.blog_id}">0</span>
                            </a>
                        </span>
                        {if $item['seo_keyword']}
                        <span class="pull-left"><span class="icon-tags icon-gray"></span> {L TAG}：{echo $me->tags($item['seo_keyword']);}</span>
                        {/if}
                    </p>
                </div>
                {/foreach}

                {$paging}
                <!--end 网文-->
            </div>
        </div><!--end span9-->
        <div class="span3">
            <!--#include virtual="/v0.1/ssi/hot_blogs.shtml"-->
            <!--#include virtual="/v0.1/ssi/tags.shtml"-->
            <!--#include virtual="/v0.1/ssi/new_guestbooks.shtml"-->
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}