{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header">
                <span class="icon-home"></span>
                {L NOW_POSITION}：<a href="{BASE_SITE_URL}">{L HOME}</a>
                <span class="divider">/</span>
                <a href="{BASE_SITE_URL}miniblog.shtml">{L MINIBLOG}</a>
                <span class="divider">/</span>
                {L MINIBLOG,DETAIL}
            </div>
            <div class="panel-body">
                <div class="panel-list media panel-miniblog">
                    <img class="media-object pull-left avatar" alt="图像" src="{COMMON_IMGCACHE}images/guest.png" />
                    <div class="media-body">
                        <div class="popover right">
                            <div class="arrow"></div>
                            <div class="popover-content">
                                <span class="muted">{echo new_date(null, $blog_info['add_time']);}</span>
                                {$blog_info.content}
                                <p class="text-right actions">
                                    <a href="#" class="muted">
                                        <span class="icon-thumbs-up icon-gray"></span>
                                        <span class="counter">0</span>
                                    </a>
                                    <a href="#" class="muted"><span class="icon-comment icon-gray"></span><span class="counter">0</span></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                {if $comments_html}
                <div class="separation-comment">{L COMMENTS,LIST}</div>
                {$comments_html}
                {/if}
            </div>
        </div><!--end span9-->
        <div class="span3">
            <!--#include virtual="/v0.1/ssi/hot_blogs.shtml"-->
            <!--#include virtual="/v0.1/ssi/tags.shtml"-->
            <!--#include virtual="/v0.1/ssi/new_guestbooks.shtml"-->
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}