{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header">
                <span class="icon-home"></span>
                {L NOW_POSITION}：<a href="{BASE_SITE_URL}">{L HOME}</a>
                <span class="divider">/</span>
                {L MINIBLOG}
            </div>
            <div class="panel-body">
                {php $meta_info_arr = array('miniblog' => ''); }
                {foreach $blog_arr $miniblog_info}
                {php $meta_info_arr['miniblog'] .= ',' . $miniblog_info['blog_id'] . '|' . $miniblog_info['add_time'];}
                {template 'include', 'miniblog-tpl'}
                {/foreach}
                {$paging}
            </div>
        </div><!--end span9-->
        <div class="span3">
            <!--#include virtual="/v0.1/ssi/hot_blogs.shtml"-->
            <!--#include virtual="/v0.1/ssi/tags.shtml"-->
            <!--#include virtual="/v0.1/ssi/new_guestbooks.shtml"-->
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}