{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header"><span class="icon-home"></span> 您现在的位置： <a href="#">首页</a> <span class="divider">/</span> <a href="miniblog.php">微博</a> <span class="divider">/</span> 微博详情</div>
            <div class="panel-body">
                <div class="blog-detail">
                    <h1>关于Yaf的一些说明</h1>
                    <p class="blog-meta">
                        <span>2013-02-21 15:33:00</span>
                        <span>来源：<a href="">nodejs.org</a></span>
                        <span>阅读：0</span>
                        <span>评论：暂无评论</span>
                    </p>
                <div class="blog-content">
				<p>最早的时候,  我记得是去年我刚加入开发组的时候,  神仙同学曾经提过, 问我是否可以考虑为PHP实现yield. 我当时做过尝试, 但是最后发现需要大改zend executor,  而当时的我还没有那么大的魄力(因为我记得当时我的第一个RFC刚刚被拒绝)认为我能说服那么多人接受这个变动,  所以后来就不了了之了.</p>
<p>    但, 现在Nikita Popov,  完整的实现了这个<a href="https://wiki.php.net/rfc/generators">RFC: Generators</a>,  并且已经提供了一个可用的<a href="https://github.com/nikic/php-src/tree/addGeneratorsSupport">实现</a>,  目前这个RFC在投票阶段, 投票形式也比较乐观,  所以如果不出大问题,  PHP5.5将会引入这一新特性.</p>
<p>    我就这里为大家简单介绍下, 这个新特性.</p>
    			             <p><span class="icon-tags"></span>标签：<a href="#">php</a>,<a href="#">js</a>,<a href="#">jquery</a></p>
    			             <p class="text-center"><a class="label label-inverse"><span class="icon-thumbs-up icon-white"></span> 顶一个</a></p>

			</div>

    			             <p>
    			                <span class="pull-right">
    			                    <span class="icon-circle-arrow-right"></span>
    			                    下一篇：<a href="#">php高级技巧</a>
    			                </span>
    			                <span class="icon-circle-arrow-left"></span>
    			                上一篇：<a href="#">php高级技巧</a>
    			             </p>
			             </div>
			             <hr />
			             <div class="row ml-10">
			             <div class="span5">
			             <div class="separation separation-guest-like"><span class="icon-heart"></span> 猜您喜欢</div>
			             <ul>
			                 <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
			             </ul>
			             </div>
			             <div class="span5 pull-right">
			             <div class="separation separation-also-read"><span class="icon-eye-open"></span> 阅读过此文的朋友还阅读了...</div>
			             <ul>
			                 <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
                    <li><a href="#">标题标题</a></li>
			             </ul>
			             </div>
			             </div>
                <div class="separation-comment">评论列表</div>
                {template 'include', 'comments'}
            </div>
        </div><!--end span9-->
        <div class="span3">
            <div class="panel">
                <div class="panel-header"><h3>热门网文</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                        <li><a href="#">标题标题</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>网文标签</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                        <li><a href="#">php</a></li>
                        <li><a href="#">javascript</a></li>
                        <li><a href="#">nodejs</a></li>
                        <li><a href="#">mongodb</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-header"><h3>最新留言</h3></div>
                <div class="panel-body">
                    <ul class="unstyled">
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                        <li><strong>mrmsl</strong>: 内容合并一个或多个数组，2为，获取内容表及内容附属表内容，3为，除2的内容外，增加统计信息</li>
                    </ul>
                </div>
            </div>
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->

{template 'include', 'footer'}