{template 'include', 'header'}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9 panel">
            <div class="panel-header">
                <span class="icon-home"></span>
                {L NOW_POSITION}：<a href="{BASE_SITE_URL}">{L HOME}</a>
                <span class="divider">/</span>
                <a href="{BASE_SITE_URL}miniblog.shtml">{L MINIBLOG}</a>
                <span class="divider">/</span>
                {L MINIBLOG,DETAIL}
            </div>
            <div class="panel-body">
                {php $miniblog_info = $blog_info; }
                {template 'include', 'miniblog-tpl'}

                {if $comments_html}
                <div class="separation-comment">{L COMMENTS,LIST}</div>
                {$comments_html}
                {/if}
            </div>
        </div><!--end span9-->
        <div class="span3">
            <!--#include virtual="/v0.1/ssi/hot_blogs.shtml"-->
            <!--#include virtual="/v0.1/ssi/tags.shtml"-->
            <!--#include virtual="/v0.1/ssi/new_guestbooks.shtml"-->
        </div><!--end  span3-->
    </div><!--end row-fluid-->
</div><!--end container-fluid-->
<script>var IS_MINIBLOG_DETAIL = true;</script>
{template 'include', 'footer'}